<?php

/**
 * This is the model base class for the table "auth_item".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AuthItem".
 *
 * Columns in table "auth_item" available as properties of the model,
 * followed by relations of table "auth_item" available as properties of the model.
 *
 * @property string $name
 * @property integer $type
 * @property string $description
 * @property string $data
 * @property string $bizrule
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property User[] $users
 * @property AuthItemChild[] $authItemChildren
 * @property AuthItemChild[] $authItemChildren1
 */
abstract class BaseAuthItem extends GxActiveRecord {

	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	public function tableName()
	{
		return 'auth_item';
	}

	public static function label($n = 1)
	{
		return Yii::t('app', 'AuthItem|AuthItems', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules()
	{
		return array(
			array('name, type', 'required'),
			array('type, created_at, updated_at', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>64),
			array('bizrule', 'length', 'max'=>45),
			array('description, data', 'safe'),
			array('description, data, bizrule, created_at, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('name, type, description, data, bizrule, created_at, updated_at', 'safe', 'on' => 'search'),
		);
	}

	public function relations()
	{
		return array(
			'users' => array(self::MANY_MANY, 'User', 'auth_assignment(itemname, userid)'),
			'authItemChildren' => array(self::HAS_MANY, 'AuthItemChild', 'parent'),
			'authItemChildren1' => array(self::HAS_MANY, 'AuthItemChild', 'child'),
		);
	}

	public function pivotModels() {
		return array(
			'users' => 'AuthAssignment',
		);
	}

	public function attributeLabels()
	{
		return array(
			'name' => Yii::t('app', 'Name'),
			'type' => Yii::t('app', 'Type'),
			'description' => Yii::t('app', 'Description'),
			'data' => Yii::t('app', 'Data'),
			'bizrule' => Yii::t('app', 'Bizrule'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'users' => null,
			'authItemChildren' => null,
			'authItemChildren1' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('name', $this->name, true);
		$criteria->compare('type', $this->type);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('bizrule', $this->bizrule, true);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

}