<?php

/**
 * This is the model base class for the table "category".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Category".
 *
 * Columns in table "category" available as properties of the model,
 * followed by relations of table "category" available as properties of the model.
 *
 * @property integer $category_id
 * @property string $category_name
 * @property string $category_description
 * @property string $category_image_url
 * @property string $category_select_button_text
 *
 * @property Product[] $products
 */
abstract class BaseCategory extends GxActiveRecord {

	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	public function tableName()
	{
		return 'category';
	}

	public static function label($n = 1)
	{
		return Yii::t('app', 'Category|Categories', $n);
	}

	public static function representingColumn() {
		return 'category_name';
	}

	public function rules()
	{
		return array(
			array('category_name, category_select_button_text', 'required'),
			array('category_name', 'length', 'max'=>200),
			array('category_image_url', 'length', 'max'=>500),
			array('category_select_button_text', 'length', 'max'=>150),
			array('category_description', 'safe'),
			array('category_description, category_image_url', 'default', 'setOnEmpty' => true, 'value' => null),
			array('category_id, category_name, category_description, category_image_url, category_select_button_text', 'safe', 'on' => 'search'),
		);
	}

	public function relations()
	{
		return array(
			'products' => array(self::HAS_MANY, 'Product', 'category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels()
	{
		return array(
			'category_id' => Yii::t('app', ''),
			'category_name' => Yii::t('app', 'Name'),
			'category_description' => Yii::t('app', 'Description'),
			'category_image_url' => Yii::t('app', 'Image Url'),
			'category_select_button_text' => Yii::t('app', 'Select Button Text'),
			'products' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('category_name', $this->category_name, true);
		$criteria->compare('category_description', $this->category_description, true);
		$criteria->compare('category_image_url', $this->category_image_url, true);
		$criteria->compare('category_select_button_text', $this->category_select_button_text, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

}