<?php

/**
 * This is the model base class for the table "auth_assignment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AuthAssignment".
 *
 * Columns in table "auth_assignment" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $itemname
 * @property integer $userid
 * @property string $bizrule
 * @property integer $created_at
 *
 */
abstract class BaseAuthAssignment extends GxActiveRecord {

	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	public function tableName()
	{
		return 'auth_assignment';
	}

	public static function label($n = 1)
	{
		return Yii::t('app', 'AuthAssignment|AuthAssignments', $n);
	}

	public static function representingColumn() {
		return array(
			'itemname',
			'userid',
		);
	}

	public function rules()
	{
		return array(
			array('itemname, userid', 'required'),
			array('userid, created_at', 'numerical', 'integerOnly'=>true),
			array('itemname', 'length', 'max'=>64),
			array('bizrule', 'length', 'max'=>45),
			array('bizrule, created_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('itemname, userid, bizrule, created_at', 'safe', 'on' => 'search'),
		);
	}

	public function relations()
	{
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels()
	{
		return array(
			'itemname' => null,
			'userid' => null,
			'bizrule' => Yii::t('app', 'Bizrule'),
			'created_at' => Yii::t('app', 'Created At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('t.itemname', $this->itemname);
		$criteria->compare('t.userid', $this->userid);
		$criteria->compare('bizrule', $this->bizrule, true);
		$criteria->compare('created_at', $this->created_at);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

}