<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'PayPal\\Service' => array($vendorDir . '/paypal/merchant-sdk-php/lib'),
    'PayPal\\PayPalAPI' => array($vendorDir . '/paypal/merchant-sdk-php/lib'),
    'PayPal\\EnhancedDataTypes' => array($vendorDir . '/paypal/merchant-sdk-php/lib'),
    'PayPal\\EBLBaseComponents' => array($vendorDir . '/paypal/merchant-sdk-php/lib'),
    'PayPal\\CoreComponentTypes' => array($vendorDir . '/paypal/merchant-sdk-php/lib'),
    'PayPal' => array($vendorDir . '/paypal/rest-api-sdk-php/lib', $vendorDir . '/paypal/sdk-core-php/lib'),
    'PEAR' => array($vendorDir . '/pear/pear_exception'),
    'Mail_mimeDecode' => array($vendorDir . '/pear/mail_mime-decode'),
    'Mail' => array($vendorDir . '/pear/mail_mime'),
    'HTTP_Request2' => array($vendorDir . '/pear/http_request2'),
    'Console' => array($vendorDir . '/pear/console_getopt'),
    '' => array($vendorDir . '/pear/pear-core-minimal/src'),
);
